# Generated by Django 5.2 on 2025-09-18 10:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_hajm_alter_order_date_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='hajm',
        ),
        migrations.AddField(
            model_name='product',
            name='capacity',
            field=models.CharField(choices=[('mini', 1), ('fullsize1', 50), ('fullsize2', 100), ('fullsize3', 150)], default=50, max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 9, 18, 13, 44, 39, 82959)),
        ),
    ]
