# Generated by Django 5.2 on 2025-09-18 10:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='capacity',
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 9, 18, 13, 49, 0, 537533)),
        ),
    ]
